- name: Install Java ANT
  yum: name=ant state=present

- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - "mariadb-server"
    - "MySQL-python"
- name: Install unzip
  yum: name=unzip state=present
- name: Install httpd
  yum: name={{ item }} state=present
  with_items:
    - "httpd"
    - "mod_ssl"
